### ISSUE TITLE
Make protobuf generation version aware

### ISSUE THREAD

**Issue by mrolla** [wercker/blueprint#29]
At the moment the libraries required to generate the `(gw\.)?pb.go` files are installed globally with a `go get` and this could potentially break compilation as the generated code may get out of sync with the gRPC libraries vendored (it happened).

A more robust approach would be borrowing few ideas from [what etcd is doing](https://github.com/coreos/etcd/blob/master/scripts/genproto.sh#L23-L24) (thanks @akupila)

**Comment by hatchan** [comment]
Solved by https://github.com/wercker/blueprint/pull/67
