### ISSUE TITLE
running init/apply resets Description in .managed.json for service template

### ISSUE THREAD

**Issue by simonlord** [wercker/blueprint#62]
Looks like the spelling/case of the description in the source template for .managed.json is different to the one being used to search/replace in code:

1. ./templates/service/.managed.json == "Tivo for VRML"
2. template.go#L17 == []string{"TiVo for VRML", "{{.Description}}"},

Notice the 'v' vs 'V'. This causes the description in .managed.json to be overwritten during an init or apply.

**Comment by hatchan** [comment]
Resolved by https://github.com/wercker/blueprint/pull/84
